# General
name: NSCoder Night
description: "Work on projects, get help, and discuss all things Apple."
url: https://alextall.github.io/minimal-block

markdown: redcarpet
highlighter: pygments

paginate: 5
permalink: /:title

# Social share and comments.
disqus-id: 
twitter: alextall
github: alextall
google: 

# RSS feed
rss-feed-limit: 10
rss-show-full: "no"
